services:
  - type: web
    name: TaskM Backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
  - type: web
    name: TaskM Frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://taskm-backend.onrender.com
